version: "3.7"

services:
  nostr-ntfy-backend:
    image: rafftyl/nostr-ntfy:1.3.0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data

  app_proxy:
    environment:
      APP_HOST: nostr-ntfy-backend
      APP_PORT: 8181
      PROXY_AUTH_ADD: "false"
    depends_on:
      - nostr-ntfy-backend
    restart: on-failure