services:
  nostr-ntfy-backend:
    image: rafftyl/nostr-ntfy:2.1.2
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data

  app_proxy:
    environment:
      APP_HOST: rafftyl-custom-store-nostr-to-ntfy-bridge_nostr-ntfy-backend_1
      APP_PORT: 8181
      PROXY_AUTH_ADD: "false"
    restart: unless-stopped
